### ISSUE TITLE
Migrate to the "unified" API (5 points)

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-gateway-sdk#1]
The new "unified" API puts the chainId into the path (it used to be a network name in the host).
We need to migrate to this new format.

E.g. instead of this URL

`https://safe-client.{network}.gnosis.io/v1` + `/safes/{address}/`

the new URL will look like this:

`https://safe-client.gnosis.io/v1` + `/{chainId}/safes/{address}/`

## Requirements
Each [path](https://github.com/gnosis/safe-react-gateway-sdk/blob/main/src/types/gateway.ts#L3) should start with a `{chainId}` parameter.

**Comment by dasanra** [comment]
We can start playing with this on staging, but backend team plans to deploy  this to production on Aug 2nd
